name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Pack
      run: electron-forge make
    - name: Inspect
      run: dir
