name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: .
